[mysql]
host="127.0.0.1"
port = 3306
password = "root"
username = "root"
db = "glow"
protocol = "tcp"
charset = "utf8"
maxIdleConn = 5
maxOpenConn = 10

[server]
port = 8080
env = "test"

[log]
file = "/var/tmp/glowblog.log"
formatter = "text"
level = "debug"  #debug info warn error fatal panic